essaiedjango/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('mot/', include('mot.urls')),
]

mot/urls.py
from django.urls import path
from .views import CreateMotView, SearchMotView, EditMotView

app_name = "mot"

urlpatterns = [
    path('create/', CreateMotView.as_view(), name="add"),
    path('search/', SearchMotView.as_view(), name="search"),
    path('edit/<int:pk>/', EditMotView.as_view(), name="edit"),
]

mot/models.py
from django.db import models

# Create your models here.
class Mot(models.Model):
    orthographe = models.CharField(max_length=32, error_messages="Un mot ne doit pas dépasser 128 caractères !")
    signification = models.TextField(error_messages="L'explication du terme est obligatoire !")
    traduction_ang = models.CharField(max_length=48, error_messages="L'équivalent en anglais doit avoir au plus 48 caractères !")
    traduction_mat = models.CharField(max_length=48, error_messages="L'équivalent en anglais doit avoir au plus 48 caractères !")
    context = models.CharField(max_length=32, error_messages="Veuillez renseigner le contexte d'utilisation du mot")
    exemple = models.TextField(blank=True, null=True) # blank=True, null=True vont toujours de paire

    # Dans le panneau d'admin des blog, ce sont les titres des blog qui seront affichés.
    def __str__(self):
        return self.orthographe

mot/forms.py
from django import forms
from mot.models import Mot

# Create your models here.
"""Formulaire lié à la classe Modèle Mot"""
class AjouterMotForm(forms.ModelForm):
    class Meta:
        model=Mot
        # Si l'on veut que notre formulaire contient tous les champs du modèle, on fera fields = "__all__"
        fields = "__all__"

        # Personnalisation des champs du formulaire
        labels={
            'orthographe':'Orthographe du mot:',
            'signification':'Donnez la signification du mot:',
            'traduction_ang':'Traduction anglaise du mot:',
            'traduction_mat':'Traduction maternelle du mot:',
            'context':'Contexte d\'utilisation du mot:',
            'exemple':'Exemple d\'utisation du mot:'
        }
        
        widgets={
            'orthographe':forms.TextInput(attrs={'placeholder': 'Ex: Bonjour'}),
            'signification':forms.Textarea(attrs={'rows':3, 'cols':10, 'placeholder':'Ex: Bonjour mon ami'}),
            'traduction_ang':forms.TextInput(attrs={'placeholder': 'Ex: Good morning'}),
            'traduction_mat':forms.TextInput(attrs={'placeholder': 'Ex: Mbembe kiri'}),
            'context':forms.TextInput(attrs={'placeholder':'Ex: Salutations'}),
            'exemple': forms.Textarea(attrs={'rows':3, 'cols':10, 'placeholder':'Ex: Bonjour mon ami'})
        }

class RechercherMotForm(forms.Form):
    mot_recherche = forms.CharField(max_length=100, required=True)

essaiedjango/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

"""Méthode CBV"""
class HomeView(TemplateView):
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        def get_context_data(self, **kwargs):
            context = super().get_context_data(**kwargs)
            return context
        

mot/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, CreateView, DetailView, UpdateView, DeleteView, ListView, FormView, View
from django.urls import reverse_lazy, reverse
from .models import Mot
from .forms import AjouterMotForm, RechercherMotForm

# Create your views here.
"""Ajouter un mot un dictionnaire"""
class CreateMotView(CreateView):
    # Le modèle dont on va se servir pour créer un mot en BD
    model = Mot
    # Formulaire lié au modèle Mot
    form_class = AjouterMotForm
    # le template rendu
    template_name = "mot/ajouter.html"
    # redirection en cas de création d'un mot avec succès
    success_url = reverse_lazy("mot:add")

    # Pour envoyer des variables à notre template
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["submit_text"] = "Enregistrer"
        context["messages"] = "Mot ajouter avec succès !!!"
        return context

    """Validation du formulaire"""
    def form_valid(self, form):
        return super().form_valid(form)

"""Rechercher un mot"""
class SearchMotView(TemplateView):
    # Le modèle dont on va se servir pour créer un mot en BD
    model = Mot
    # template rendu
    template_name = "mot/rechercher.html"
    # contexte
    context_object_name = 'mots'
    message = ""

    def get(self, request, *args, **kwargs):
        if self.request.method == 'GET':
            mot_recherche = self.request.GET.get('mot_cherche', '')
            self.mot_trouve = Mot.objects.filter(orthographe__icontains=mot_recherche)
            if not self.mot_trouve:
                self.message = f"Le terme '{mot_recherche}' n'existe pas dans le dictionnaire"
                print(self.message)
            else:
                self.message = 'Mot retrouvé'
                print(self.message)
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        return super().get_context_data(resultat=self.mot_trouve, message=self.message, **kwargs)

class EditMotView(UpdateView):
    # Le modèle dont on va se servir pour modifier un mot en BD
    model = Mot
    # Formulaire lié au modèle Mot
    form_class = AjouterMotForm
    # template rendu
    template_name = "mot/modifier.html"
    # redirection en cas de création d'un mot avec succès
    success_url = reverse_lazy("mot:search")

    # Pour envoyer des variables à notre template
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["submit_text"] = "Sauvegarder"
        context["messages"] = "Mot modifié avec succès !!!"
        return context

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>DICO-MLET - {% block title %}{% endblock %}</title>
    <!-- Insertion des fichiers CSS -->
    <link href="{% static 'css/all.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    {% block css %}{% endblock %}
</head>
<body>
    <!--Main Wrapper-->
	<div class="wrapper">
		<!-- HEADER -->
        {% include "include/header.html" %}

        <!-- CONTENT -->
        {% block content %}
            <!-- content -->
        {% endblock %}

		<!-- FOOTER -->
        {% include "include/footer.html" %}
	</div>

    <!-- Insertion des fichiers JAVASCRIPT -->
	<script src="{% static 'js/all.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    {% block js %}{% endblock %}
</body>
</html>

templates/include/footer.html
{% load static %}

templates/include/header.html
<nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}">Dico - MLET</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'home' %}">Accueil
            <span class="visually-hidden">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'mot:search' %}">Rechercher</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'mot:add' %}">Ajouter</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">A propos !</a>
        </li>
      </ul>
      <form class="d-flex" action="{% url 'mot:search' %}">
        <input class="form-control me-sm-2" type="search" placeholder="Rechercher un mot dans le dictionnaire" name="mot_cherche" size="40">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Rechercher</button>
      </form>
    </div>
  </div>
</nav>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Accueil{% endblock %}

{% block content %}
    <div class="container mt-5">
        <div class="jumbotron mt-5">
          <h1 class="display-3">DICO-MLET !</h1>
          <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
          <hr class="my-4">
          <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
          <p class="lead">
            <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
          </p>
        </div>
    </div>
{% endblock %}

templates/mot/ajouter.html
{% extends 'base.html' %}

{% load static %}
{% load django_bootstrap5 %}

{% block title %}Ajouter un mot{% endblock %}

{% block content %}
    <div class="container mt-5">
        <div class="row">
            <h4>Ajouter un nouveau mot au dictionnaire</h4>
            <hr>
        </div>
        <div class="row mt-5">
            <form method="POST" class="form-group">
                {% csrf_token %}
                <div class="row">
                    <div class="col-sm-4">
                        {% bootstrap_field form.orthographe %}
                    </div>
                    <div class="col-sm-4">
                        {% bootstrap_field form.traduction_ang %}
                    </div>
                    <div class="col-sm-4">
                        {% bootstrap_field form.traduction_mat %}
                    </div>
                </div>
                <div class="row mt-5">
                    <div class="col-sm-6">
                        {% bootstrap_field form.signification %}
                    </div>
                    <div class="col-sm-6">
                        {% bootstrap_field form.exemple %}
                    </div>
                </div>
                <div class="row mt-5">
                    <div class="col-sm-12">
                        {% bootstrap_field form.context %}
                    </div>
                </div>
                <hr>
                <input type="submit" class="btn btn-sm btn-primary" value="{{ submit_text }}">
                <input type="reset" class="btn btn-sm btn-danger" value="Annuler">
            </form>
        </div>
    </div>
{% endblock %}

templates/mot/modifier.html
{% extends 'base.html' %}

{% load static %}
{% load django_bootstrap5 %}

{% block title %}Modifier un mot{% endblock %}

{% block content %}
    <div class="container mt-5">
        <div class="row">
            <h4>Modifier le mot au dictionnaire</h4>
            <hr>
        </div>
        <div class="row mt-5">
            <form method="POST" class="form-group">
                {% csrf_token %}
                <div class="row">
                    <div class="col-sm-4">
                        {% bootstrap_field form.orthographe %}
                    </div>
                    <div class="col-sm-4">
                        {% bootstrap_field form.traduction_ang %}
                    </div>
                    <div class="col-sm-4">
                        {% bootstrap_field form.traduction_mat %}
                    </div>
                </div>
                <div class="row mt-5">
                    <div class="col-sm-6">
                        {% bootstrap_field form.signification %}
                    </div>
                    <div class="col-sm-6">
                        {% bootstrap_field form.exemple %}
                    </div>
                </div>
                <div class="row mt-5">
                    <div class="col-sm-12">
                        {% bootstrap_field form.context %}
                    </div>
                </div>
                <hr>
                <input type="submit" class="btn btn-sm btn-primary" value="{{ submit_text }}">
                <input type="reset" class="btn btn-sm btn-danger" value="Annuler">
            </form>
        </div>
    </div>
{% endblock %}

templates/mot/rechercher.html
{% extends 'base.html' %}

{% load static %}
{% load django_bootstrap5 %}

{% block title %}Ajouter un mot{% endblock %}

{% block content %}
    <div class="container mt-5">
        <div class="row">
            <h4>Chercher un mot dans le dictionnaire</h4>
            <hr>
        </div>
        <div class="row mb-5">
            <form action="" class="form-group">
                <div class="input-group mb-3">
                  <input type="search" class="form-control" placeholder="Rechercher un mot dans le dictionnaire" name="mot_cherche" value="{{ request.GET.mot_cherche }}"
                         aria-label="Rechercher un mot dans le dictionnaire" aria-describedby="button-addon2">
                  <button class="btn btn-primary" type="submit" id="button-addon2">Rechercher</button>
                </div>
            </form>
        </div>
        {% if message != "" %}
            <div class="jumbotron border-1">
                <h3 class="display-6">Résultat</h3>
                <p class="lead">{{ message }}</p>
                <hr class="mb-4">
                <table class="table table-hover">
                    {% for mot in resultat %}
                        <div class="row">
                            <tr>
                                <th>Ortographe: </th>
                                <td>{{ mot.orthographe }}</td>
                            </tr>
                            <tr>
                                <th>Traduction en anglais: </th>
                                <td>{{ mot.traduction_ang }}</td>
                            </tr>
                            <tr>
                                <th>Traduction en langue maternelle: </th>
                                <td>{{ mot.traduction_mat }}</td>
                            </tr>
                            <tr>
                                <th>Description: </th>
                                <td>{{ mot.signification }}</td>
                            </tr>
                            <tr>
                                <th>Exemple d'utilisation: </th>
                                <td>{{ mot.exemple }}</td>
                            </tr>
                            <tr>
                                <th>Contexte d'utilisation: </th>
                                <td>{{ mot.context }}</td>
                            </tr>
                        </div>
                        <div class="row">
                            <div class="col-3">
                                <a href="{% url 'mot:edit' mot.pk %}" class="btn btn-sm btn-primary">Modifier la description du mot</a>
                            </div>
                            <div class="col-3 ms-auto">
                                <a href="" class="btn btn-sm btn-danger">Effacer ce mot du dictionnaire</a>
                            </div>
                        </div>
                    {% endfor %}
                </table>
            </div>
        {% endif %}
    </div>
{% endblock %}

templates/mot/supprimer.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Ajouter un mot{% endblock %}

{% block content %}
    <div class="container mt-5">
        <div class="row">
            <h4>Supprimer un mot du dictionnaire</h4>
            <hr>
        </div>
    </div>
{% endblock %}